export interface Prefecture {
  code: string
  english: string
  japanese: string
  shortName: string
  region: string
}
export const prefecturesOptions: Prefecture[] = [
  {
    code: "hokkaido",
    english: "Hokkaido",
    japanese: "北海道",
    shortName: "北海道",
    region: "北海道",
  },
  {
    code: "aomori",
    english: "Aomori",
    japanese: "青森県",
    shortName: "青森",
    region: "東北",
  },
  {
    code: "iwate",
    english: "Iwate",
    japanese: "岩手県",
    shortName: "岩手",
    region: "東北",
  },
  {
    code: "miyagi",
    english: "Miyagi",
    japanese: "宮城県",
    shortName: "宮城",
    region: "東北",
  },
  {
    code: "akita",
    english: "Akita",
    japanese: "秋田県",
    shortName: "秋田",
    region: "東北",
  },
  {
    code: "yamagata",
    english: "Yamagata",
    japanese: "山形県",
    shortName: "山形",
    region: "東北",
  },
  {
    code: "fukushima",
    english: "Fukushima",
    japanese: "福島県",
    shortName: "福島",
    region: "東北",
  },
  {
    code: "ibaraki",
    english: "Ibaraki",
    japanese: "茨城県",
    shortName: "茨城",
    region: "関東",
  },
  {
    code: "tochigi",
    english: "Tochigi",
    japanese: "栃木県",
    shortName: "栃木",
    region: "関東",
  },
  {
    code: "gunma",
    english: "Gunma",
    japanese: "群馬県",
    shortName: "群馬",
    region: "関東",
  },
  {
    code: "saitama",
    english: "Saitama",
    japanese: "埼玉県",
    shortName: "埼玉",
    region: "関東",
  },
  {
    code: "chiba",
    english: "Chiba",
    japanese: "千葉県",
    shortName: "千葉",
    region: "関東",
  },
  {
    code: "tokyo",
    english: "Tokyo",
    japanese: "東京都",
    shortName: "東京",
    region: "関東",
  },
  {
    code: "kanagawa",
    english: "Kanagawa",
    japanese: "神奈川県",
    shortName: "神奈川",
    region: "関東",
  },
  {
    code: "niigata",
    english: "Niigata",
    japanese: "新潟県",
    shortName: "新潟",
    region: "中部",
  },
  {
    code: "toyama",
    english: "Toyama",
    japanese: "富山県",
    shortName: "富山",
    region: "関東",
  },
  {
    code: "ishikawa",
    english: "Ishikawa",
    japanese: "石川県",
    shortName: "石川",
    region: "関東",
  },
  {
    code: "Fukui",
    english: "Fukui",
    japanese: "福井県",
    shortName: "福井",
    region: "関東",
  },
  {
    code: "yamanashi",
    english: "Yamanashi",
    japanese: "山梨県",
    shortName: "山梨",
    region: "関東",
  },
  {
    code: "nagano",
    english: "Nagano",
    japanese: "長野県",
    shortName: "長野",
    region: "関東",
  },
  {
    code: "gifu",
    english: "Gifu",
    japanese: "岐阜県",
    shortName: "岐阜",
    region: "関東",
  },
  {
    code: "shizuoka",
    english: "Shizuoka",
    japanese: "静岡県",
    shortName: "静岡",
    region: "関東",
  },
  {
    code: "aichi",
    english: "Aichi",
    japanese: "愛知県",
    shortName: "愛知",
    region: "関東",
  },
  {
    code: "mie",
    english: "Mie",
    japanese: "三重県",
    shortName: "三重",
    region: "関東",
  },
  {
    code: "shiga",
    english: "Shiga",
    japanese: "滋賀県",
    shortName: "滋賀",
    region: "近畿",
  },
  {
    code: "kyoto",
    english: "Kyoto",
    japanese: "京都府",
    shortName: "京都",
    region: "近畿",
  },
  {
    code: "osaka",
    english: "Osaka",
    japanese: "大阪府",
    shortName: "大阪",
    region: "近畿",
  },
  {
    code: "hyogo",
    english: "Hyogo",
    japanese: "兵庫県",
    shortName: "兵庫",
    region: "近畿",
  },
  {
    code: "nara",
    english: "Nara",
    japanese: "奈良県",
    shortName: "奈良",
    region: "近畿",
  },
  {
    code: "wakayama",
    english: "Wakayama",
    japanese: "和歌山県",
    shortName: "和歌山",
    region: "近畿",
  },
  {
    code: "tottori",
    english: "Tottori",
    japanese: "鳥取県",
    shortName: "鳥取",
    region: "中国",
  },
  {
    code: "shimane",
    english: "Shimane",
    japanese: "島根県",
    shortName: "島根",
    region: "中国",
  },
  {
    code: "okayama",
    english: "Okayama",
    japanese: "岡山県",
    shortName: "岡山",
    region: "中国",
  },
  {
    code: "hiroshima",
    english: "Hiroshima",
    japanese: "広島県",
    shortName: "広島",
    region: "中国",
  },
  {
    code: "yamaguchi",
    english: "Yamaguchi",
    japanese: "山口県",
    shortName: "山口",
    region: "中国",
  },
  {
    code: "tokushima",
    english: "Tokushima",
    japanese: "徳島県",
    shortName: "徳島",
    region: "四国",
  },
  {
    code: "kagawa",
    english: "Kagawa",
    japanese: "香川県",
    shortName: "香川",
    region: "四国",
  },
  {
    code: "ehime",
    english: "Ehime",
    japanese: "愛媛県",
    shortName: "愛媛",
    region: "四国",
  },
  {
    code: "kochi",
    english: "Kochi",
    japanese: "高知県",
    shortName: "高知",
    region: "四国",
  },
  {
    code: "fukuoka",
    english: "Fukuoka",
    japanese: "福岡県",
    shortName: "福岡",
    region: "九州",
  },
  {
    code: "saga",
    english: "Saga",
    japanese: "佐賀県",
    shortName: "佐賀",
    region: "九州",
  },
  {
    code: "nagasaki",
    english: "Nagasaki",
    japanese: "長崎県",
    shortName: "長崎",
    region: "九州",
  },
  {
    code: "kumamoto",
    english: "Kumamoto",
    japanese: "熊本県",
    shortName: "熊本",
    region: "九州",
  },
  {
    code: "oita",
    english: "Oita",
    japanese: "大分県",
    shortName: "大分",
    region: "九州",
  },
  {
    code: "miyazaki",
    english: "Miyazaki",
    japanese: "宮崎県",
    shortName: "宮崎",
    region: "九州",
  },
  {
    code: "kagoshima",
    english: "Kagoshima",
    japanese: "鹿児島県",
    shortName: "鹿児島",
    region: "九州",
  },
  {
    code: "okinawa",
    english: "Okinawa",
    japanese: "沖縄県",
    shortName: "沖縄",
    region: "九州",
  },
]
