-- AlterTable
ALTER TABLE "Webhook" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "resource" DROP NOT NULL,
ALTER COLUMN "data" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "result" DROP NOT NULL;
